name: Changelog

on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - '.github/**'
      - 'test-server.sh'
  pull_request:
    types: [closed]

permissions:
  contents: write 

jobs:
  changelog:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create empty changelog (if missing)
        run: |
          if [ ! -f "CHANGELOG.md" ]; then
            echo "# Changelog" > CHANGELOG.md
            echo "" >> CHANGELOG.md
            echo "All notable changes to this project will be documented in this file." >> CHANGELOG.md
          fi

      - name: Generate Changelog
        uses: ardalanamini/auto-changelog@v4.0.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-types: |
            feat: Features
            fix: Bug Fixes
            perf: Performance
            refactor: Refactoring
            docs: Documentation
          default-commit-type: Other Changes
          release-name: v1.0.0
          include-compare-link: true
          include-pr-links: true

      - name: Debug file changes
        run: |
          git status
          git diff

      - name: Commit and push changelog
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add CHANGELOG.md
          git commit -m "chore: update changelog" || echo "No changes to commit"
          git push origin HEAD
