name: Changelog

on:
  push:
    branches: [main]
    paths-ignore:  # Files that WON'T trigger changelog updates
      - 'README.md'
      - '.github/**'
      - 'test-server.sh'
  pull_request:
    types: [closed]

jobs:
  changelog:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: current version
        id: version
        run: |
          # Extract version from package.json or other source
          # Example for package.json:
          VERSION=$(grep -m1 '"version"' package.json | cut -d'"' -f4)
          echo "version=${VERSION:-0.1.0}" >> $GITHUB_OUTPUT
          echo "Using version: $VERSION"

      - name: Generate Changelog
        uses: ardalanamini/auto-changelog@v4.0.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output: CHANGELOG.md
          commit-types: |
            feat: Features
            fix: Bug Fixes
            perf: Performance
            refactor: Refactoring
            docs: Documentation
          default-commit-type: Other Changes
          release-name: v${{ steps.version.outputs.version }}
          breaking-pattern: '^break|BREAKING CHANGE'
          include-compare-link: true
          include-pr-links: true
          mention-authors: true

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add CHANGELOG.md
          git commit -m "chore: update changelog [skip ci]" || echo "No changes to commit"
          git push