name: Changelog

on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - '.github/**'
      - 'test-server.sh'
  pull_request:
    types: [closed]

jobs:
  changelog:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Critical for getting full commit history

      - name: Setup initial changelog
        run: |
          if [ ! -f "CHANGELOG.md" ]; then
            echo "# Changelog" > CHANGELOG.md
            echo "" >> CHANGELOG.md
            echo "All notable changes to this project will be documented in this file." >> CHANGELOG.md
          fi

      - name: Generate Changelog
        uses: ardalanamini/auto-changelog@v4.0.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output: CHANGELOG.md
          commit-types: |
            feat: Features
            fix: Bug Fixes
            perf: Performance Improvements
            refactor: Code Refactoring
            docs: Documentation
          default-commit-type: Other Changes
          breaking-pattern: '^break|BREAKING CHANGE'
          include-compare-link: true
          include-pr-links: true

      - name: Verify changelog content
        run: |
          echo "Generated changelog content:"
          cat CHANGELOG.md
          echo ""
          echo "Line count: $(wc -l < CHANGELOG.md)"
          if [ ! -s "CHANGELOG.md" ]; then
            echo "Error: CHANGELOG.md is empty!"
            exit 1
          fi

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add CHANGELOG.md
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update changelog"
            git push
          fi