name: Changelog

on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - '.github/**'
      - 'test-server.sh'
  pull_request:
    types: [closed]

jobs:
  changelog:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Changelog
        uses: ardalanamini/auto-changelog@v4.0.2
        with:
          github-token: ${{ github.token }}
          commit-types: |
            feat: Features
            fix: Bug Fixes
            perf: Performance Improvements
            refactor: Code Refactoring
            docs: Documentation
          default-commit-type: Other Changes
          include-compare-link: true
          include-pr-links: true
          release-name: v${{ steps.version.outputs.version }}
          mention-authors: true
          mention-new-contributors: true
          include-commit-links: true
          semver: true
          use-github-autolink: true

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add CHANGELOG.md
          git commit -m "chore: update changelog" || echo "No changes to commit"
          git push